name: maulen_super_handsome
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #state managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #http 
  dio: ^5.3.0
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  #dependency injection
  get_it: ^7.6.0
  #gen
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1  
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  #l10n
  intl: any
  flutter_localization: any
#firebase 
  firebase_core: ^2.17.0
  firebase_auth: ^4.7.2
  firebase_dynamic_links: ^5.3.4
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.9.3

  #others
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  flutter_gen: ^5.3.1
  auto_route: ^7.7.1
  auto_route_generator: ^7.2.0
  google_fonts: ^5.1.0
  line_icons: ^2.0.3
  email_validator: ^2.1.17
  lint: ^2.1.2
  firebase_storage: ^11.2.6
  flutter_hooks: ^0.20.2
  uuid: ^4.1.0
  logger: ^2.0.2+1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6
flutter_gen:
    output: lib/src/gen 
    line_length: 80 

    integrations:
     flutter_svg: true
     flare_flutter: true
     lottie: true  


flutter:
 
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

  
